import type { NextPage } from "next";
import Head from "next/head";
import LoadingScreen from "components/layout/loadingScreen";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../firebase/clientApp";
// import { useAuthSession } from "utils/hooks";

const Home: NextPage = () => {
  // const [user, loading, error] = useAuthSession();
  const [user, loading, error] = useAuthState(auth);

  return (
    <div>
      <Head>
        <title>Faculty Workload</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoadingScreen />
    </div>
  );
};

export default Home;
